### ISSUE TITLE
Code shoot motors for amp scoring

### ISSUE THREAD

**Issue by PalladiumSpider** [first-team-93-new-apple-corp/Robot2024#25]
Elevator telescopes out then motors are slow enough for amp scoring (Shooting Note instead of linear actuator)

**Comment by jsmmr2** [comment]
Currently waiting on a piece of polycarbonate to be mounted to the front of the shooter so that we can drop the note in. When tested last time with a piece of wood, it went to an amp setpoint and dropped it in.
