### ISSUE TITLE
Look into AdvantageScope and AdvantageKit

### ISSUE THREAD

**Issue by jsmmr2** [first-team-93-new-apple-corp/Robot2024#40]
There is a software built into WPILib called AdvantageScope, it should allow us to see where the robot is in 3d space, simulate the drivetrain, and show a lot of data. (Similar to Shuffleboard/Elastic, but it might not actually be used at comps)

AdvantageKit is a logging software made to go along well with AdvantageScope which will let us log our data for visualization better

**Comment by Captagonal** [comment]
Advantage Kit will not work with a Tuner X generated swerve, so we will not be able to use it, we will still be able to use Advantage Scope to visualize our swerve whilst driving or during simulation

**Comment by jsmmr2** [comment]
Is there a certain reason why or just it won't work?
@Captagonal

**Comment by Captagonal** [comment]
I tried it and it wasn’t working and after some searching through the FRC discord I learned that the Phoenix 6 swerve classes aren’t cleanly compatible with advantage kit
